-- Store settings (checkout, payments, delivery). Server-only: read/written with the secret key.
create table if not exists public.pristine_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
alter table public.pristine_settings enable row level security;
revoke all on public.pristine_settings from anon, authenticated;

-- Checkout orders. Totals are always computed on the server from catalog prices.
create table if not exists public.pristine_orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  status text not null default 'pending_payment'
    check (status in ('pending_payment','paid','pay_later','processing','ready','out_for_delivery','completed','cancelled','refunded')),
  name text not null,
  email text not null,
  phone text not null,
  fulfillment text not null check (fulfillment in ('delivery','pickup')),
  address text,
  matched_address text,
  lat double precision,
  lng double precision,
  miles numeric(8,1),
  items jsonb not null,
  subtotal numeric(10,2) not null,
  delivery_fee numeric(10,2) not null default 0,
  tax numeric(10,2) not null default 0,
  total numeric(10,2) not null,
  payment_method text not null check (payment_method in ('paypal','venmo','card','pay_later')),
  paypal_order_id text unique,
  paypal_capture_id text,
  payer_email text,
  notes text,
  admin_notes text
);
alter table public.pristine_orders enable row level security;
revoke all on public.pristine_orders from anon, authenticated;
create index if not exists pristine_orders_created_idx on public.pristine_orders (created_at desc);
create index if not exists pristine_orders_email_idx on public.pristine_orders (lower(email));

-- Stripe card payments
alter table public.pristine_orders add column if not exists stripe_payment_intent text unique;
